#!/bin/bash
set -e

echo "CangjieX has been installed."
echo "Please log out and back in, then enable CangjieX in System Settings > Keyboard > Input Sources."

killall "Yahoo! KeyKey" >/dev/null 2>&1 || true
killall "CangjieX" >/dev/null 2>&1 || true

exit 0
